### ISSUE TITLE
Please publish Cargo.lock with the crate

### ISSUE THREAD

**Issue by polyzen** [ryym/textris#2]
`error: the lock file needs to be updated but --locked was passed to prevent this`

**Comment by polyzen** [comment]
I see the lock file isn't shipped with the crate.

Looks like this would be needed:
https://github.com/rust-lang/cargo/issues/5654

**Comment by ryym** [comment]
Thanks for reporting.
So did you build from the source code downloaded by `cargo install`?
I'm not sure it is a common practice, but I agree it is better if the downloaded crate contains a lock file.

It seems that the error only occurs in `textris-0.1.0`. The latest version is 0.2.0 and it can be built with `cargo build --locked` without the error in my environment, even if the lock file does not exist.
I confirmed this by doing:

- `cargo install textris`
- `cd` to the source directory `.cargo/registry/src/github.com-hash/textris-0.2.0`
- `cargo build --locked`

**Comment by polyzen** [comment]
I download crates manually, actually:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=textris#n12

I believe the `cargo install` generated `Cargo.lock` for you. Perhaps it wouldn't have worked with `cargo install --locked textris`.

**Comment by polyzen** [comment]
I've learned unstable Cargo features require Cargo nightly. Will bump this once it's stabilized.

**Comment by ryym** [comment]
> I've learned unstable Cargo features require Cargo nightly.

Yeah, that makes me hesitate to use the `publish-lockfile` feature.
Thanks any way.

**Comment by polyzen** [comment]
> [Cargo will be changed to always include Cargo.lock in the .crate file if the package has binaries or examples.](https://github.com/rust-lang/cargo/issues/5654#issuecomment-497863987)
